GET http://localhost:3000/profiles?age=20

GET http://localhost:3000/profiles/1

POST http://localhost:3000/profiles
Content-Type: application/json

{
  "name": "John Doe",
  "description": "Software Engineer"
}
