### Get Profile
GET http://localhost:3000/profiles

{{
  $global.profileId=response.parsedBody[0].id;
}}

### Get Profile By ID
GET http://localhost:3000/profiles/{{$global.profileId}}

### Create Profile
POST http://localhost:3000/profiles
Content-Type: application/json

{
  "name": "John Doe",
  "description": "Software Engineer"
}

PUT http://localhost:3000/profiles/1
Content-Type: application/json

{
  "name": "John Doe",
  "description": "Senior Software Engineer"
}
